// <auto-generated />
using System;
using Decidr.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Decidr.Infrastructure.Migrations
{
    [DbContext(typeof(DecidrDbContext))]
    [Migration("20250908011950_AddCardActivity")]
    partial class AddCardActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.CardActivityEntity", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDate");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDisliked");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean")
                        .HasColumnName("IsLiked");

                    b.HasKey("CardId", "UserId")
                        .HasName("CardActivity_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("CardActivities", "app");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.CardEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ImageUrl");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint")
                        .HasColumnName("SetId");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.HasKey("Id")
                        .HasName("Cards_pkey");

                    b.HasIndex("SetId");

                    b.ToTable("Cards", "app");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.SetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDate");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("Sets_pkey");

                    b.ToTable("Sets", "app");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.SetMemberEntity", b =>
                {
                    b.Property<long>("SetId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddedById")
                        .HasColumnType("bigint")
                        .HasColumnName("AddedById");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDate");

                    b.Property<bool>("IsUnread")
                        .HasColumnType("boolean")
                        .HasColumnName("IsUnread");

                    b.HasKey("SetId", "UserId")
                        .HasName("SetMembers_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("SetMembers", "app");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.CardActivityEntity", b =>
                {
                    b.HasOne("Decidr.Infrastructure.EntityFramework.Models.CardEntity", "Card")
                        .WithMany("Activities")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Decidr.Infrastructure.EntityFramework.Models.UserEntity", "User")
                        .WithMany("CardActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.CardEntity", b =>
                {
                    b.HasOne("Decidr.Infrastructure.EntityFramework.Models.SetEntity", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.SetMemberEntity", b =>
                {
                    b.HasOne("Decidr.Infrastructure.EntityFramework.Models.SetEntity", "Set")
                        .WithMany("Members")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Decidr.Infrastructure.EntityFramework.Models.UserEntity", "User")
                        .WithMany("SetMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.CardEntity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.SetEntity", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Decidr.Infrastructure.EntityFramework.Models.UserEntity", b =>
                {
                    b.Navigation("CardActivities");

                    b.Navigation("SetMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
